name = "streamlist"
compatibility_date = "2024-04-01"
compatibility_flags = ["nodejs_compat_v2"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "streamlist-db"
database_id = "541b5cbd-1898-4994-8abd-557b5a57abf5"

[vars]
TMDB_API_BASE_URL = "https://api.themoviedb.org/3"